services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: 160290
      POSTGRES_PASSWORD: 160290
    network_mode: bridge
